keys: &keys
  - &desktop age1d7l44trdac37hfx7yrtw4zf7re3k39tzjeav70z9t9xv9ur5wsmshge2pw
  - &laptop age1yqh025casyzy6sw68m08xreftvswjf9eqwnvcaytga6jvehdhejqr6mf04
  - &lab age19f8l20tkls4v0uh3wuucj44pxpsj9l85vj4q2rx03rnag0cpy39swmtyhm
  - &vps age1fwntxgz0yf0vwl0an6y4ptzelsu70asj5yq4ag7eglftjy0ye32s367d3v
creation_rules:
  - path_regex: secrets/common.yaml
    key_groups:
      - age: *keys

  # hosts
  - path_regex: secrets/hosts/lab.yaml
    key_groups:
      - age:
          - *desktop
          - *lab
  - path_regex: secrets/hosts/vps.yaml
    key_groups:
      - age:
          - *desktop
          - *vps
  - path_regex: secrets/hosts/desktop.yaml
    key_groups:
      - age:
          - *desktop
  - path_regex: secrets/hosts/laptop.yaml
    key_groups:
      - age:
          - *laptop
