keys: &keys
  - &diana age1d7l44trdac37hfx7yrtw4zf7re3k39tzjeav70z9t9xv9ur5wsmshge2pw
  - &pluto age1yqh025casyzy6sw68m08xreftvswjf9eqwnvcaytga6jvehdhejqr6mf04
  - &apollo age19f8l20tkls4v0uh3wuucj44pxpsj9l85vj4q2rx03rnag0cpy39swmtyhm
  - &jupiter age17zujvv98knpzwa8aqqe2cw7v5v08t34qkd5vruyzjczwzat8usnq6la3ry
creation_rules:
  - path_regex: secrets/common.yaml
    key_groups:
      - age: *keys

  # hosts
  - path_regex: secrets/hosts/apollo.yaml
    key_groups:
      - age:
          - *apollo
          - *diana
  - path_regex: secrets/hosts/jupiter.yaml
    key_groups:
      - age:
          - *jupiter
          - *diana
  - path_regex: secrets/hosts/diana.yaml
    key_groups:
      - age:
          - *diana
          - *pluto
  - path_regex: secrets/hosts/pluto.yaml
    key_groups:
      - age:
          - *pluto
          - *diana
