#!/bin/sh
# watch mpris for changes & update the status bar

# play/pause
while read -r line; do
    pkill -RTMIN+4 someblocks
done < <(/home/etc/scripts/player metadata -f "{{ status }} {{ title }}" -F)
