[Service]
Environment=WINDOW=screen
Environment=CONTAINER=mp4
Environment=QUALITY=high
Environment=BITRATE_MODE=vbr
Environment=CODEC=auto
Environment=AUDIO_CODEC=opus
Environment=AUDIO_DEVICES="-a 'app-inverse:spotify-player|app-inverse:Firefox'"
Environment=FRAMERATE=60
Environment=REPLAYDURATION=30
Environment=OUTPUTDIR=%h/usr/vid/replays
Environment=MAKEFOLDERS=no
Environment=COLOR_RANGE=limited
Environment=KEYINT=5
Environment=ENCODER=gpu
Environment=SCRIPT=%h/etc/scripts/handle-replay
Environment=ADDITIONAL_ARGS="-fm vfr"

ExecStart=
ExecStart=gpu-screen-recorder -v no -w "${WINDOW}" -s "${OUTPUT_RESOLUTION}" -c "${CONTAINER}" -q "${QUALITY}" -k "${CODEC}" -ac "${AUDIO_CODEC}" $AUDIO_DEVICES -f "${FRAMERATE}" -r "${REPLAYDURATION}" -o "${OUTPUTDIR}" -df "${MAKEFOLDERS}" -sc "${SCRIPT}" $ADDITIONAL_ARGS -cr "${COLOR_RANGE}" -keyint "${KEYINT}" -restore-portal-session "${RESTORE_PORTAL_SESSION}" -encoder "${ENCODER}" -bm "${BITRATE_MODE}"
