#!/bin/sh

device=$1
unmuted_icon=$2
muted_icon=$3

if wpctl get-volume $device | grep -q "MUTED"; then
	icon="$muted_icon"
else
	icon="$unmuted_icon"
fi

volume=$(wpctl get-volume $device | awk -F": " '{print $2 * 100}')
echo "^us(/home/etc/scripts/keys/volume $device +)^ds(/home/etc/scripts/keys/volume $device -)^lm(/home/etc/scripts/keys/mute $device)$icon $volume%^lm()^us()^ds()"
