default_access.rules = [
	{
		matches = [
			{ "application.process.binary" = "vesktop.bin" }
			{ "pipewire.access" = "flatpak" }
		]

		actions = {
			update-props = {
				default_permissions = "r"
			}
		}
	}
]
