{
  imports = [
    ./boot.nix
    ./dev.nix
    ./firewall.nix
    ./flatpak.nix
    ./fonts.nix
    ./git.nix
    ./home.nix
    ./ld.nix
    ./locale.nix
    ./media.nix
    ./nix.nix
    ./packages.nix
    ./persistence.nix
    ./remote-unlock.nix
    ./security.nix
    ./sops.nix
    ./ssh.nix
    ./swap.nix
    ./user.nix
    ./xdg.nix
  ];
}
