pulse.rules = [
	{
		# disable auto mic gain for applications that dont follow their own settings
		matches = [
			{ application.process.binary = "vesktop.bin" }
		],
		actions = { quirks = [ block-source-volume ] }
	}
]
